/**
 * Mapping of VR question types into topic groups for the UI.
 * Used by both the subject overview and exam board detail APIs.
 */

export interface SubGroupDef {
  id: string;
  name: string;
  description?: string;
  questionTypes: string[];
}

export interface TopicGroupDef {
  id: string;
  name: string;
  icon: string;
  color: string;
  questionTypes: string[];
  /** When defined, subtopics are grouped by sub-group instead of one per question type */
  subGroups?: SubGroupDef[];
}

export const VR_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "alphabet-letters",
    name: "Alphabet & Letter Sequences",
    icon: "Type",
    color: "blue",
    questionTypes: [
      "alphabet_series",
      "alphabetical_order",
      "letter_pairs",
      "letter_sequences",
    ],
  },
  {
    id: "word-building",
    name: "Word Building & Spelling",
    icon: "Puzzle",
    color: "purple",
    questionTypes: [
      "anagram",
      "compound_words",
      "forming_new_words",
      "four_letter_completion",
      "hidden_words",
      "letter_completion",
      "letter_completion_double",
      "missing_letters",
      "move_a_letter",
      "three_letter_completion",
      "word_completion",
      "word_ladder",
      "word_swap",
    ],
  },
  {
    id: "word-meanings",
    name: "Word Meanings",
    icon: "BookOpen",
    color: "teal",
    questionTypes: [
      "multiple_meanings",
      "synonyms",
      "antonyms",
      "opposite_meaning",
      "similar_meaning",
      "odd_one_out",
      "sentence_completion_analogies",
    ],
  },
  {
    id: "codes-equations",
    name: "Codes & Equations",
    icon: "KeyRound",
    color: "orange",
    questionTypes: [
      "letter_equations",
      "letter_word_codes",
      "number_codes",
      "missing_number_equations",
    ],
  },
  {
    id: "logic-puzzles",
    name: "Logic & Puzzles",
    icon: "Lightbulb",
    color: "amber",
    questionTypes: [
      "logic_puzzles",
      "analogies",
      "sentence_completion",
      "comprehension",
      "number_patterns",
    ],
  },
];

export const MATHS_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "fractions-decimals",
    name: "Fractions & Decimals",
    icon: "BookOpen",
    color: "blue",
    questionTypes: [
      // Fractions of Amounts
      "fraction_of_an_amount",
      "fraction_of_an_amount_discount",
      "fraction_of_an_amount_discounts",
      "fraction_of_an_amount_money",
      "fraction_of_an_amount_remainder",
      "fraction_of_an_amount_finding_remainder",
      "fraction_of_an_amount_spending",
      "fraction_of_an_amount_working_backwards",
      "fraction_of_amount_with_conversion",
      "reverse_fraction_of_an_amount",
      "finding_the_whole_from_a_part",
      "fractions_of_mixed_amounts",
      "fraction_of_a_fraction",
      "multiplying_fractions",
      "comparing_fractions",
      "comparing_fractions_with_conversion",
      "fractions_and_money",
      "fractions_and_time",
      "fractions_and_ratios",
      "discrete_grouping",
      "discrete_grouping_with_remainder",
      "multi_step_discrete_grouping",
      // Mixed Numbers
      "fraction_of_a_mixed_number",
      "fraction_of_a_mixed_number_remainder",
      "mixed_numbers",
      "mixed_numbers_and_fractions_of_amounts",
      "mixed_numbers_with_money",
      "mixed_numbers_and_money",
      "mixed_numbers_and_distance",
      "mixed_numbers_and_division",
      "mixed_numbers_and_multiplication",
      "mixed_numbers_and_unit_conversion",
      "mixed_numbers_and_volumes",
      "mixed_numbers_units",
      "distance_and_mixed_numbers",
      "fractions_with_mixed_numbers",
      "adding_mixed_numbers",
      "subtracting_mixed_numbers",
      "dividing_a_mixed_number_by_a_fraction",
      "dividing_a_mixed_number_by_an_integer",
      "pure_mixed_arithmetic",
      "pure_mixed_arithmetic_division",
      "pure_mixed_arithmetic_money",
      "pure_mixed_arithmetic_multiplication",
      "mixed_arithmetic",
      "mixed_number_arithmetic",
      "mixed_numbers_arithmetic",
      "fractions_and_decimals",
      "fractions_and_percentages",
      // Multi-Step
      "multi_step_fraction_calculation",
      "multi_step_fraction_problem",
      "multi_step_fractions_of_amounts",
      "multi_step_fractions",
      "multi_step_discounts",
      "multi_step_problem",
      "multi_step_problem_solving",
      "sequential_remainder_fractions",
      "sequential_remainder_fractions_working_backwards",
      "sequential_remainder_fractions_as_a_fraction",
      "sequential_fractions_addition",
      "sequential_fractions_of_original",
      "sequential_remainder",
      "sequential_remainder_working_backwards",
      "working_backwards",
      "working_backwards_with_fractions",
      // Word Problems
      "linguistic_parsing",
      "linguistic_parsing_comparison",
      "linguistic_parsing_difference",
      "linguistic_parsing_and_addition",
      "linguistic_parsing_with_fractions",
    ],
    subGroups: [
      {
        id: "fractions-of-amounts",
        name: "Fractions of Amounts",
        description: "Calculate fractions of quantities, with remainders and conversions",
        questionTypes: [
          "fraction_of_an_amount",
          "fraction_of_an_amount_discount",
          "fraction_of_an_amount_discounts",
          "fraction_of_an_amount_money",
          "fraction_of_an_amount_remainder",
          "fraction_of_an_amount_finding_remainder",
          "fraction_of_an_amount_spending",
          "fraction_of_an_amount_working_backwards",
          "fraction_of_amount_with_conversion",
          "reverse_fraction_of_an_amount",
          "finding_the_whole_from_a_part",
          "fractions_of_mixed_amounts",
          "fraction_of_a_fraction",
          "multiplying_fractions",
          "comparing_fractions",
          "comparing_fractions_with_conversion",
          "fractions_and_money",
          "fractions_and_time",
          "fractions_and_ratios",
          "discrete_grouping",
          "discrete_grouping_with_remainder",
          "multi_step_discrete_grouping",
        ],
      },
      {
        id: "mixed-numbers",
        name: "Mixed Numbers & Arithmetic",
        description: "Work with mixed numbers, decimals and fraction arithmetic",
        questionTypes: [
          "fraction_of_a_mixed_number",
          "fraction_of_a_mixed_number_remainder",
          "mixed_numbers",
          "mixed_numbers_and_fractions_of_amounts",
          "mixed_numbers_with_money",
          "mixed_numbers_and_money",
          "mixed_numbers_and_distance",
          "mixed_numbers_and_division",
          "mixed_numbers_and_multiplication",
          "mixed_numbers_and_unit_conversion",
          "mixed_numbers_and_volumes",
          "mixed_numbers_units",
          "distance_and_mixed_numbers",
          "fractions_with_mixed_numbers",
          "adding_mixed_numbers",
          "subtracting_mixed_numbers",
          "dividing_a_mixed_number_by_a_fraction",
          "dividing_a_mixed_number_by_an_integer",
          "pure_mixed_arithmetic",
          "pure_mixed_arithmetic_division",
          "pure_mixed_arithmetic_money",
          "pure_mixed_arithmetic_multiplication",
          "mixed_arithmetic",
          "mixed_number_arithmetic",
          "mixed_numbers_arithmetic",
          "fractions_and_decimals",
          "fractions_and_percentages",
        ],
      },
      {
        id: "multi-step-fractions",
        name: "Multi-Step Problems",
        description: "Sequential remainders, working backwards and multi-step fraction problems",
        questionTypes: [
          "multi_step_fraction_calculation",
          "multi_step_fraction_problem",
          "multi_step_fractions_of_amounts",
          "multi_step_fractions",
          "multi_step_discounts",
          "multi_step_problem",
          "multi_step_problem_solving",
          "sequential_remainder_fractions",
          "sequential_remainder_fractions_working_backwards",
          "sequential_remainder_fractions_as_a_fraction",
          "sequential_fractions_addition",
          "sequential_fractions_of_original",
          "sequential_remainder",
          "sequential_remainder_working_backwards",
          "working_backwards",
          "working_backwards_with_fractions",
        ],
      },
      {
        id: "word-problems-fractions",
        name: "Word Problems",
        description: "Parse and solve worded fraction and arithmetic problems",
        questionTypes: [
          "linguistic_parsing",
          "linguistic_parsing_comparison",
          "linguistic_parsing_difference",
          "linguistic_parsing_and_addition",
          "linguistic_parsing_with_fractions",
        ],
      },
    ],
  },
];

export const MEASUREMENTS_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "measurements",
    name: "Measurements",
    icon: "Gauge",
    color: "teal",
    questionTypes: [
      // Reading Scales
      "reading_a_scale",
      "reading_mass_scales",
      "reading_volume_scales",
      "reading_scales_mass",
      "reading_scales_volume",
      "scale_reading",
      // Time
      "time_calculation",
      "time_conversion",
      "time_conversions",
      "time_and_rate",
      "timetable_calculation",
      "timetable_interpretation",
      "multi_step_time_calculation",
      "converting_decimal_hours_to_minutes",
      "converting_decimal_minutes_to_seconds",
      "working_backwards_with_time",
      // Unit Conversion
      "unit_conversion",
      "metric_conversion",
      "metric_imperial_conversion",
      "metric_and_imperial_conversion",
      "imperial_to_metric_length_area",
      "imperial_to_metric_volume",
      "multi_step_conversion",
      "multi_step_conversions",
      "temperature_conversion_rule",
      "temperature_conversion",
      "imperial_metric_conversion",
      // Volume & Capacity
      "capacity",
      "volume",
      "volume_multiplication",
      "volume_subtraction",
      "volume_scaling",
      "volume_scaling_of_a_cube",
      "volume_scaling_of_a_cuboid",
      "volume_and_scaling",
      "volume_surface_area",
      "reverse_volume_scaling",
      "area_and_volume_scaling",
      "multi_step_volume_problem",
      "division_with_remainder_volume",
      "finding_a_fraction_of_a_volume",
      "liquid_volume_calculation",
      // Speed, Distance & Area
      "speed_distance_time",
      "average_speed",
      "scale_and_speed",
      "area_and_perimeter",
      "area_and_scaling",
      "multi_step_measurement",
      "proportional_reasoning",
    ],
    subGroups: [
      {
        id: "scales-reading",
        name: "Reading Scales",
        description: "Read and interpret mass, volume and other scales",
        questionTypes: [
          "reading_a_scale",
          "reading_mass_scales",
          "reading_volume_scales",
          "reading_scales_mass",
          "reading_scales_volume",
          "scale_reading",
        ],
      },
      {
        id: "time",
        name: "Time",
        description: "Time calculations, conversions and timetables",
        questionTypes: [
          "time_calculation",
          "time_conversion",
          "time_conversions",
          "time_and_rate",
          "timetable_calculation",
          "timetable_interpretation",
          "multi_step_time_calculation",
          "converting_decimal_hours_to_minutes",
          "converting_decimal_minutes_to_seconds",
          "working_backwards_with_time",
        ],
      },
      {
        id: "unit-conversion",
        name: "Unit Conversion",
        description: "Convert between metric, imperial and temperature units",
        questionTypes: [
          "unit_conversion",
          "metric_conversion",
          "metric_imperial_conversion",
          "metric_and_imperial_conversion",
          "imperial_to_metric_length_area",
          "imperial_to_metric_volume",
          "multi_step_conversion",
          "multi_step_conversions",
          "temperature_conversion_rule",
          "temperature_conversion",
          "imperial_metric_conversion",
        ],
      },
      {
        id: "volume-capacity",
        name: "Volume & Capacity",
        description: "Calculate volumes, capacity and scaling problems",
        questionTypes: [
          "capacity",
          "volume",
          "volume_multiplication",
          "volume_subtraction",
          "volume_scaling",
          "volume_scaling_of_a_cube",
          "volume_scaling_of_a_cuboid",
          "volume_and_scaling",
          "volume_surface_area",
          "reverse_volume_scaling",
          "area_and_volume_scaling",
          "multi_step_volume_problem",
          "division_with_remainder_volume",
          "finding_a_fraction_of_a_volume",
          "liquid_volume_calculation",
        ],
      },
      {
        id: "speed-distance",
        name: "Speed, Distance & Rate",
        description: "Speed-distance-time problems and proportional reasoning",
        questionTypes: [
          "speed_distance_time",
          "average_speed",
          "scale_and_speed",
          "area_and_perimeter",
          "area_and_scaling",
          "multi_step_measurement",
          "proportional_reasoning",
        ],
      },
    ],
  },
];

export const GEOMETRY_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "geometry",
    name: "Geometry",
    icon: "Compass",
    color: "orange",
    questionTypes: [
      // Area & Perimeter
      "area_and_perimeter",
      "area_and_subtraction",
      "area_and_unit_conversion",
      "area_of_a_triangle",
      "area_of_composite_shapes",
      "area_and_borders",
      "circles_and_perimeter",
      "complex_area",
      "composite_area",
      "fractional_area",
      "fractional_shading",
      "percentage_area",
      "percentages_and_area",
      "perimeter_and_cost",
      "perimeter_of_composite_shapes",
      "scale_drawings",
      // 3D Shapes
      "3d_area_volume",
      "3d_packing",
      "3d_surface_area",
      "3d_views_and_surface_area",
      "3d_visualisation",
      "3d_volume",
      "compound_3d_volume",
      "cutting_cubes",
      "multi_step_3d_geometry",
      "nets_of_3d_shapes",
      "packing_cubes",
      "surface_area",
      "surface_area_and_cost",
      "surface_area_of_cuboids",
      "volume_and_conversion",
      "volume_and_packing",
      "volume_of_a_cuboid",
      "volume_of_composite_shapes",
      // Tiling & Shape Nesting
      "tiling",
      "tiling_and_cost",
      "tiling_and_percentages",
      "tiling_and_proportions",
      "tiling_with_a_border",
      "tiling_with_borders",
      "tiling_packing",
      "shape_nesting",
      "shape_nesting_and_area",
      "shape_nesting_and_percentages",
      // Angles & Coordinates
      "clock_angles",
      "angles_and_time",
      "angles_on_a_line",
      "cartesian_coordinates",
      // Algebraic Geometry
      "algebraic_geometry",
    ],
    subGroups: [
      {
        id: "area-perimeter",
        name: "Area & Perimeter",
        description: "Calculate areas, perimeters and work with composite shapes",
        questionTypes: [
          "area_and_perimeter",
          "area_and_subtraction",
          "area_and_unit_conversion",
          "area_of_a_triangle",
          "area_of_composite_shapes",
          "area_and_borders",
          "circles_and_perimeter",
          "complex_area",
          "composite_area",
          "fractional_area",
          "fractional_shading",
          "percentage_area",
          "percentages_and_area",
          "perimeter_and_cost",
          "perimeter_of_composite_shapes",
          "scale_drawings",
        ],
      },
      {
        id: "3d-shapes",
        name: "3D Shapes & Volume",
        description: "Surface area, volume, nets and 3D visualisation",
        questionTypes: [
          "3d_area_volume",
          "3d_packing",
          "3d_surface_area",
          "3d_views_and_surface_area",
          "3d_visualisation",
          "3d_volume",
          "compound_3d_volume",
          "cutting_cubes",
          "multi_step_3d_geometry",
          "nets_of_3d_shapes",
          "packing_cubes",
          "surface_area",
          "surface_area_and_cost",
          "surface_area_of_cuboids",
          "volume_and_conversion",
          "volume_and_packing",
          "volume_of_a_cuboid",
          "volume_of_composite_shapes",
        ],
      },
      {
        id: "tiling-nesting",
        name: "Tiling & Shape Nesting",
        description: "Tiling patterns, packing and shape nesting problems",
        questionTypes: [
          "tiling",
          "tiling_and_cost",
          "tiling_and_percentages",
          "tiling_and_proportions",
          "tiling_with_a_border",
          "tiling_with_borders",
          "tiling_packing",
          "shape_nesting",
          "shape_nesting_and_area",
          "shape_nesting_and_percentages",
        ],
      },
      {
        id: "angles-coordinates",
        name: "Angles & Coordinates",
        description: "Clock angles, angles on a line and Cartesian coordinates",
        questionTypes: [
          "clock_angles",
          "angles_and_time",
          "angles_on_a_line",
          "cartesian_coordinates",
        ],
      },
      {
        id: "algebraic-geometry",
        name: "Algebraic Geometry",
        description: "Solve geometry problems using algebraic reasoning",
        questionTypes: [
          "algebraic_geometry",
        ],
      },
    ],
  },
];

export const PERCENTAGES_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "percentages",
    name: "Percentages",
    icon: "Percent",
    color: "blue",
    questionTypes: [
      "basic_percentage_calculation",
      "percentage_increase",
      "percentage_decrease",
      "percentage_of_a_quantity",
      "percentage_of_a_percentage",
      "percentage_of_a_remainder",
      "remaining_percentage",
      "percentage_and_fraction_conversion",
      "percentage_fraction_conversion",
      "percentage_change_and_fractions",
      "percentage_change_and_new_fraction",
      "fractions_and_percentages",
      "reverse_percentage",
      "reverse_percentages",
      "reverse_percentages_discount",
      "reverse_percentages_loss",
      "reverse_percentages_profit",
      "reverse_percentages_vat",
      "reverse_percentage_and_change",
      "reverse_percentage_change",
      "reverse_percentage_logic",
      "reverse_percentage_smallest_number",
      "reverse_percentage_and_sequential_change",
      "reverse_area_percentages",
      "reverse_demographic_percentages",
      "reverse_spatial_percentages",
      "compound_percentages",
      "compound_percentages_remainder",
      "compound_set_percentages",
      "sequential_percentages",
      "sequential_percentage_change",
      "sequential_percentage_logic",
      "sequential_percentage_removal",
      "sequential_change_and_final_percentage",
      "financial_logic",
      "sequential_financial_logic",
      "multi_step_percentages",
      "multi_step_percentage_calculation",
      "multi_step_percentage_and_units",
    ],
    subGroups: [
      {
        id: "basic-percentages",
        name: "Basic Percentages",
        description: "Calculate simple percentages, increases and decreases",
        questionTypes: [
          "basic_percentage_calculation",
          "percentage_increase",
          "percentage_decrease",
          "percentage_of_a_quantity",
          "percentage_of_a_percentage",
          "percentage_of_a_remainder",
          "remaining_percentage",
        ],
      },
      {
        id: "percentage-conversions",
        name: "Percentage Conversions",
        description: "Convert between percentages and fractions",
        questionTypes: [
          "percentage_and_fraction_conversion",
          "percentage_fraction_conversion",
          "percentage_change_and_fractions",
          "percentage_change_and_new_fraction",
          "fractions_and_percentages",
        ],
      },
      {
        id: "reverse-percentages",
        name: "Reverse Percentages",
        description: "Work backwards to find the original value",
        questionTypes: [
          "reverse_percentage",
          "reverse_percentages",
          "reverse_percentages_discount",
          "reverse_percentages_loss",
          "reverse_percentages_profit",
          "reverse_percentages_vat",
          "reverse_percentage_and_change",
          "reverse_percentage_change",
          "reverse_percentage_logic",
          "reverse_percentage_smallest_number",
          "reverse_percentage_and_sequential_change",
          "reverse_area_percentages",
          "reverse_demographic_percentages",
          "reverse_spatial_percentages",
        ],
      },
      {
        id: "compound-sequential",
        name: "Compound & Sequential Percentages",
        description: "Apply multiple percentage changes one after another",
        questionTypes: [
          "compound_percentages",
          "compound_percentages_remainder",
          "compound_set_percentages",
          "sequential_percentages",
          "sequential_percentage_change",
          "sequential_percentage_logic",
          "sequential_percentage_removal",
          "sequential_change_and_final_percentage",
        ],
      },
      {
        id: "financial-logic",
        name: "Financial Logic",
        description: "Solve money problems using percentages",
        questionTypes: [
          "financial_logic",
          "sequential_financial_logic",
          "multi_step_percentages",
          "multi_step_percentage_calculation",
          "multi_step_percentage_and_units",
        ],
      },
    ],
  },
];

export const ALGEBRA_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "algebra",
    name: "Algebra",
    icon: "Variable",
    color: "blue",
    questionTypes: [
      "linear_progression",
      "disguised_algebra",
      "grouped_variable_sums",
      "associated_properties",
      "associated_property_logic",
      "linear_intersection",
      "simultaneous_equations",
      "simultaneous_equations_disguised",
      "simultaneous_logic",
      "multi_variable_algebra",
      "multi_variable_ratio",
      "multi_variable_ratio_constraints",
      "multi_variable_ratios",
      "logic_puzzle",
    ],
    subGroups: [
      {
        id: "linear-algebra",
        name: "Linear Algebra & Progressions",
        description: "Continue patterns and find where sequences meet",
        questionTypes: [
          "linear_progression",
          "linear_intersection",
          "disguised_algebra",
        ],
      },
      {
        id: "variable-sums",
        name: "Variable Sums & Properties",
        description: "Add unknowns and use linked properties",
        questionTypes: [
          "grouped_variable_sums",
          "associated_properties",
          "associated_property_logic",
        ],
      },
      {
        id: "simultaneous-equations",
        name: "Simultaneous Equations & Logic",
        description: "Solve two or more equations at the same time",
        questionTypes: [
          "simultaneous_equations",
          "simultaneous_equations_disguised",
          "simultaneous_logic",
          "logic_puzzle",
        ],
      },
      {
        id: "multi-variable",
        name: "Multi-Variable & Ratios",
        description: "Work with multiple unknowns and ratio constraints",
        questionTypes: [
          "multi_variable_algebra",
          "multi_variable_ratio",
          "multi_variable_ratio_constraints",
          "multi_variable_ratios",
        ],
      },
    ],
  },
];

export const PROBABILITY_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "probability",
    name: "Probability & Statistics",
    icon: "Dice",
    color: "purple",
    questionTypes: [
      "qualitative_likelihood",
      "expected_frequency",
      "complementary_fractions",
      "probability_from_a_set",
      "sample_space_counting",
      "sample_space_combined_probability",
      "sample_space_without_replacement",
      "combined_statistics_probability",
      "changing_probability",
    ],
    subGroups: [
      {
        id: "basic-probability",
        name: "Basic Probability",
        description: "Judge likelihood and work out expected frequencies",
        questionTypes: [
          "qualitative_likelihood",
          "expected_frequency",
          "probability_from_a_set",
        ],
      },
      {
        id: "complementary-fractions",
        name: "Complementary Fractions",
        description: "Find the probability of something not happening",
        questionTypes: [
          "complementary_fractions",
        ],
      },
      {
        id: "sample-space",
        name: "Sample Space & Counting",
        description: "List and count all possible outcomes",
        questionTypes: [
          "sample_space_counting",
          "sample_space_combined_probability",
          "sample_space_without_replacement",
        ],
      },
      {
        id: "combined-statistics",
        name: "Combined Statistics & Probability",
        description: "Use statistics and probability together",
        questionTypes: [
          "combined_statistics_probability",
          "changing_probability",
        ],
      },
    ],
  },
];

export const ENGLISH_SPAG_TOPIC_GROUPS: TopicGroupDef[] = [
  {
    id: "word-classes",
    name: "Word Classes",
    icon: "BookOpen",
    color: "blue",
    questionTypes: [
      "identifying_word_classes",
      "identifying_word_classes_pronouns",
      "identifying_word_classes_determiners",
      "identifying_word_classes_adverbs",
      "identifying_word_classes_determiners_pronouns_adverbs",
      "word_classes",
      "word_classes_pronouns",
      "word_classes_determiners",
      "word_classes_adverbs",
      "word_classes:_pronouns",
      "word_classes:_determiners",
      "word_classes:_adverbs",
    ],
    subGroups: [
      {
        id: "word-classes-general",
        name: "Identifying Word Classes",
        description: "Pick out nouns, verbs, adjectives and other word classes",
        questionTypes: [
          "identifying_word_classes",
          "word_classes",
        ],
      },
      {
        id: "word-classes-pronouns",
        name: "Pronouns",
        description: "Identify pronouns like he, she, it, they",
        questionTypes: [
          "identifying_word_classes_pronouns",
          "word_classes_pronouns",
          "word_classes:_pronouns",
        ],
      },
      {
        id: "word-classes-determiners",
        name: "Determiners",
        description: "Identify determiners like the, a, some, every",
        questionTypes: [
          "identifying_word_classes_determiners",
          "word_classes_determiners",
          "word_classes:_determiners",
        ],
      },
      {
        id: "word-classes-adverbs",
        name: "Adverbs",
        description: "Identify adverbs that describe how, when or where",
        questionTypes: [
          "identifying_word_classes_adverbs",
          "word_classes_adverbs",
          "word_classes:_adverbs",
        ],
      },
      {
        id: "word-classes-mixed",
        name: "Mixed Word Classes",
        description: "Identify determiners, pronouns and adverbs in context",
        questionTypes: [
          "identifying_word_classes_determiners_pronouns_adverbs",
        ],
      },
    ],
  },
  {
    id: "prefixes-suffixes",
    name: "Prefixes & Suffixes",
    icon: "Puzzle",
    color: "purple",
    questionTypes: [
      "prefix_meanings",
      "prefix_meanings_anti_mis_re_sub",
      "prefix_meanings_re_sub",
      "prefix_meanings_mis",
      "prefix_meanings_anti",
      "prefix_meanings_sub",
      "prefixes",
      "suffix_application",
      "suffix_application_ate_ise_ify_ment",
      "suffix_application_ment",
      "suffix_application_ate_ise_ify",
      "suffix_application_ise_ify_ate_ment",
      "suffix_application_ify",
    ],
    subGroups: [
      {
        id: "prefix-meanings",
        name: "Prefix Meanings",
        description: "Understand what prefixes like re-, un-, mis- mean",
        questionTypes: [
          "prefix_meanings",
          "prefix_meanings_anti_mis_re_sub",
          "prefix_meanings_re_sub",
          "prefix_meanings_mis",
          "prefix_meanings_anti",
          "prefix_meanings_sub",
          "prefixes",
        ],
      },
      {
        id: "suffix-application",
        name: "Suffix Application",
        description: "Add suffixes like -ment, -ify, -ise to complete words",
        questionTypes: [
          "suffix_application",
          "suffix_application_ate_ise_ify_ment",
          "suffix_application_ment",
          "suffix_application_ate_ise_ify",
          "suffix_application_ise_ify_ate_ment",
          "suffix_application_ify",
        ],
      },
    ],
  },
  {
    id: "vocabulary",
    name: "Vocabulary",
    icon: "Lightbulb",
    color: "teal",
    questionTypes: [
      "synonyms_and_antonyms",
      "synonyms",
      "antonyms",
      "formal_vs_informal_vocabulary",
      "formal_vs_informal",
      "formal_and_informal_vocabulary",
    ],
    subGroups: [
      {
        id: "synonyms-antonyms",
        name: "Synonyms & Antonyms",
        description: "Find words with similar or opposite meanings",
        questionTypes: [
          "synonyms_and_antonyms",
          "synonyms",
          "antonyms",
        ],
      },
      {
        id: "formal-informal",
        name: "Formal vs Informal",
        description: "Choose the right level of formality for writing",
        questionTypes: [
          "formal_vs_informal_vocabulary",
          "formal_vs_informal",
          "formal_and_informal_vocabulary",
        ],
      },
    ],
  },
  {
    id: "clauses-sentences",
    name: "Clauses & Sentences",
    icon: "Type",
    color: "orange",
    questionTypes: [
      "relative_clauses_and_relative_pronouns",
      "relative_clauses",
      "relative_pronouns",
      "subordinate_vs_main_clauses",
      "main_clauses",
      "subordinate_clauses",
    ],
    subGroups: [
      {
        id: "relative-clauses",
        name: "Relative Clauses & Pronouns",
        description: "Spot relative clauses and pronouns like who, which, that",
        questionTypes: [
          "relative_clauses_and_relative_pronouns",
          "relative_clauses",
          "relative_pronouns",
        ],
      },
      {
        id: "main-subordinate",
        name: "Main & Subordinate Clauses",
        description: "Tell apart main clauses and subordinate clauses",
        questionTypes: [
          "subordinate_vs_main_clauses",
          "main_clauses",
          "subordinate_clauses",
        ],
      },
    ],
  },
  {
    id: "punctuation",
    name: "Punctuation",
    icon: "KeyRound",
    color: "amber",
    questionTypes: [
      "colons_and_semi_colons_in_lists_or_boundary_sentences",
      "colons_and_semi_colons",
      "colons_in_lists",
      "colons_and_semi_colons_in_lists",
      "semi_colons_in_lists",
      "semi_colons",
      "dashes_and_hyphens_for_clarity",
      "dashes_for_clarity",
      "dashes_and_hyphens",
      "hyphens_for_clarity",
      "possessive_apostrophes_plural",
      "possessive_apostrophes_singular_vs_plural",
      "possessive_apostrophes",
      "possessive_apostrophes_singular",
    ],
    subGroups: [
      {
        id: "colons-semicolons",
        name: "Colons & Semi-colons",
        description: "Use colons and semi-colons in lists and sentences",
        questionTypes: [
          "colons_and_semi_colons_in_lists_or_boundary_sentences",
          "colons_and_semi_colons",
          "colons_in_lists",
          "colons_and_semi_colons_in_lists",
          "semi_colons_in_lists",
          "semi_colons",
        ],
      },
      {
        id: "dashes-hyphens",
        name: "Dashes & Hyphens",
        description: "Use dashes and hyphens to make meaning clearer",
        questionTypes: [
          "dashes_and_hyphens_for_clarity",
          "dashes_for_clarity",
          "dashes_and_hyphens",
          "hyphens_for_clarity",
        ],
      },
      {
        id: "apostrophes",
        name: "Possessive Apostrophes",
        description: "Show belonging with apostrophes for singular and plural",
        questionTypes: [
          "possessive_apostrophes_plural",
          "possessive_apostrophes_singular_vs_plural",
          "possessive_apostrophes",
          "possessive_apostrophes_singular",
        ],
      },
    ],
  },
  {
    id: "verb-grammar",
    name: "Verb Grammar",
    icon: "Zap",
    color: "green",
    questionTypes: [
      "modal_verbs_for_possibility_or_obligation",
      "modal_verbs_for_obligation",
      "modal_verbs_for_possibility",
      "modal_verbs_possibility",
      "modal_verbs",
      "passive_and_active_voice_transformation",
      "passive_and_active_voice",
      "passive_to_active_voice_transformation",
      "active_to_passive_voice_transformation",
      "active_and_passive_voice",
      "the_subjunctive_mood",
    ],
    subGroups: [
      {
        id: "modal-verbs",
        name: "Modal Verbs",
        description: "Identify modal verbs showing possibility or obligation",
        questionTypes: [
          "modal_verbs_for_possibility_or_obligation",
          "modal_verbs_for_obligation",
          "modal_verbs_for_possibility",
          "modal_verbs_possibility",
          "modal_verbs",
        ],
      },
      {
        id: "active-passive",
        name: "Active & Passive Voice",
        description: "Understand and transform active and passive voice",
        questionTypes: [
          "passive_and_active_voice_transformation",
          "passive_and_active_voice",
          "passive_to_active_voice_transformation",
          "active_to_passive_voice_transformation",
          "active_and_passive_voice",
        ],
      },
      {
        id: "subjunctive",
        name: "The Subjunctive Mood",
        description: "Use the subjunctive mood for formal or hypothetical statements",
        questionTypes: [
          "the_subjunctive_mood",
        ],
      },
    ],
  },
  {
    id: "sentence-structure",
    name: "Sentence Structure",
    icon: "LayoutGrid",
    color: "red",
    questionTypes: [
      "fronted_adverbials_and_comma_placement",
    ],
    subGroups: [
      {
        id: "fronted-adverbials",
        name: "Fronted Adverbials",
        description: "Use fronted adverbials with correct comma placement",
        questionTypes: [
          "fronted_adverbials_and_comma_placement",
        ],
      },
    ],
  },
];

/** Build a reverse map: questionType → topicGroupId */
const _qtToGroup = new Map<string, string>();
for (const groups of [VR_TOPIC_GROUPS, MATHS_TOPIC_GROUPS, MEASUREMENTS_TOPIC_GROUPS, GEOMETRY_TOPIC_GROUPS, PERCENTAGES_TOPIC_GROUPS, ALGEBRA_TOPIC_GROUPS, PROBABILITY_TOPIC_GROUPS, ENGLISH_SPAG_TOPIC_GROUPS]) {
  for (const g of groups) {
    for (const qt of g.questionTypes) {
      _qtToGroup.set(qt, g.id);
    }
  }
}

export function getTopicGroupId(questionType: string): string | undefined {
  return _qtToGroup.get(questionType);
}

/** Child-friendly descriptions for each question type */
export const QUESTION_TYPE_DESCRIPTIONS: Record<string, string> = {
  alphabet_series: "Continue letter patterns in the right order",
  alphabetical_order: "Put words in the correct A\u2013Z order",
  letter_pairs: "Spot and match letter pairs",
  letter_sequences: "Spot and extend letter patterns",
  anagram: "Rearrange letters to make a real word",
  compound_words: "Join two words to make a new one",
  forming_new_words: "Create new words from given letters",
  four_letter_completion: "Find the four-letter word that fits",
  hidden_words: "Spot words hiding inside a sentence",
  letter_completion: "Fill in the blanks to complete words",
  letter_completion_double: "Fill in the blanks to complete words",
  missing_letters: "Fill in the missing letters",
  move_a_letter: "Shift one letter to fix both words",
  three_letter_completion: "Find the three-letter word that fits",
  word_completion: "Complete the word with the right letters",
  word_ladder: "Change one letter at a time to make new words",
  word_swap: "Swap two words to make the sentence correct",
  multiple_meanings: "Find the word that has more than one meaning",
  synonyms: "Match words with similar meanings",
  antonyms: "Match words with opposite meanings",
  opposite_meaning: "Find the word with the opposite meaning",
  similar_meaning: "Find the word with a similar meaning",
  odd_one_out: "Find the word that doesn't belong",
  sentence_completion_analogies: "Complete the sentence with the right word pair",
  letter_equations: "Solve equations using letter values",
  letter_word_codes: "Crack the code by matching letters",
  number_codes: "Decode numbers to find the answer",
  missing_number_equations: "Find the missing number in the equation",
  logic_puzzles: "Use clues to work out the answer",
  analogies: "Find the connection between pairs of words",
  sentence_completion: "Choose the right word to complete the sentence",
  comprehension: "Read a passage and answer questions",
  number_patterns: "Spot the pattern in a number sequence",
  // Maths - Fractions
  fraction_of_an_amount: "Find a fraction of a given number",
  fraction_of_an_amount_discount: "Work out discounts using fractions",
  fraction_of_an_amount_money: "Calculate fractions of money amounts",
  fraction_of_an_amount_remainder: "Find what's left after taking a fraction",
  fraction_of_an_amount_spending: "Work out spending using fractions",
  reverse_fraction_of_an_amount: "Find the original amount from a fraction",
  fractions_of_mixed_amounts: "Calculate fractions of mixed amounts",
  discrete_grouping: "Split items into equal groups",
  discrete_grouping_with_remainder: "Group items and find remainders",
  fraction_of_a_mixed_number: "Find a fraction of a mixed number",
  fraction_of_a_mixed_number_remainder: "Mixed numbers with remainders",
  mixed_numbers_and_fractions_of_amounts: "Combine mixed numbers and fractions",
  mixed_numbers_with_money: "Mixed number calculations with money",
  dividing_a_mixed_number_by_a_fraction: "Divide a mixed number by a fraction",
  dividing_a_mixed_number_by_an_integer: "Divide a mixed number by a whole number",
  pure_mixed_arithmetic: "Arithmetic with mixed numbers",
  fractions_and_decimals: "Convert between fractions and decimals",
  fractions_and_percentages: "Convert between fractions and percentages",
  multi_step_fraction_calculation: "Solve fraction problems with multiple steps",
  multi_step_fraction_problem: "Multi-step fraction word problems",
  multi_step_fractions_of_amounts: "Multiple fraction calculations in one problem",
  multi_step_discounts: "Calculate discounts with multiple steps",
  sequential_remainder_fractions: "Find remainders after taking fractions in order",
  sequential_remainder_fractions_working_backwards: "Work backwards through fraction steps",
  sequential_remainder_fractions_as_a_fraction: "Express sequential remainders as fractions",
  fraction_of_an_amount_discounts: "Work out discounts using fractions",
  fraction_of_an_amount_finding_remainder: "Find what's left after taking a fraction",
  fraction_of_an_amount_working_backwards: "Find the starting amount from a fraction",
  fraction_of_amount_with_conversion: "Calculate fractions with unit conversions",
  finding_the_whole_from_a_part: "Work out the whole when you know a part",
  fraction_of_a_fraction: "Find a fraction of another fraction",
  multiplying_fractions: "Multiply fractions together",
  comparing_fractions: "Compare fractions to find which is bigger",
  comparing_fractions_with_conversion: "Compare fractions using conversions",
  fractions_and_money: "Solve fraction problems involving money",
  fractions_and_time: "Solve fraction problems involving time",
  fractions_and_ratios: "Work with fractions and ratios together",
  multi_step_discrete_grouping: "Group items in multiple steps",
  mixed_numbers: "Work with mixed numbers",
  mixed_numbers_and_money: "Mixed number calculations with money",
  mixed_numbers_and_distance: "Mixed number problems with distances",
  mixed_numbers_and_division: "Divide with mixed numbers",
  mixed_numbers_and_multiplication: "Multiply with mixed numbers",
  mixed_numbers_and_unit_conversion: "Mixed numbers with unit conversions",
  mixed_numbers_and_volumes: "Mixed number problems with volumes",
  mixed_numbers_units: "Mixed numbers with different units",
  distance_and_mixed_numbers: "Distance problems using mixed numbers",
  fractions_with_mixed_numbers: "Combine fractions and mixed numbers",
  adding_mixed_numbers: "Add mixed numbers together",
  subtracting_mixed_numbers: "Subtract mixed numbers",
  pure_mixed_arithmetic_division: "Divide mixed numbers",
  pure_mixed_arithmetic_money: "Mixed number arithmetic with money",
  pure_mixed_arithmetic_multiplication: "Multiply mixed numbers",
  mixed_arithmetic: "Arithmetic with mixed numbers",
  mixed_number_arithmetic: "Arithmetic with mixed numbers",
  mixed_numbers_arithmetic: "Arithmetic with mixed numbers",
  multi_step_fractions: "Solve fraction problems with multiple steps",
  multi_step_problem: "Solve problems with multiple steps",
  multi_step_problem_solving: "Solve problems with multiple steps",
  sequential_fractions_addition: "Add fractions in sequence",
  sequential_fractions_of_original: "Find sequential fractions of the original",
  sequential_remainder: "Find remainders after taking fractions in order",
  sequential_remainder_working_backwards: "Work backwards through remainder steps",
  working_backwards: "Work backwards to find the starting value",
  working_backwards_with_fractions: "Work backwards through fraction steps",
  linguistic_parsing: "Read carefully and pick out the right numbers",
  linguistic_parsing_comparison: "Compare values described in words",
  linguistic_parsing_difference: "Find differences from worded problems",
  linguistic_parsing_and_addition: "Add values described in words",
  linguistic_parsing_with_fractions: "Fraction problems described in words",
  // Measurements
  reading_a_scale: "Read values from a scale",
  reading_mass_scales: "Read mass from a weighing scale",
  reading_volume_scales: "Read volume from a measuring container",
  reading_scales_mass: "Read mass from a weighing scale",
  reading_scales_volume: "Read volume from a measuring container",
  scale_reading: "Read values from different scales",
  time_calculation: "Calculate durations and times",
  time_conversion: "Convert between time units",
  time_conversions: "Convert between time units",
  time_and_rate: "Solve problems involving time and rates",
  timetable_calculation: "Work out times from a timetable",
  timetable_interpretation: "Read and understand timetables",
  multi_step_time_calculation: "Solve time problems with multiple steps",
  converting_decimal_hours_to_minutes: "Convert decimal hours to minutes",
  converting_decimal_minutes_to_seconds: "Convert decimal minutes to seconds",
  working_backwards_with_time: "Work backwards to find a start time",
  unit_conversion: "Convert between different units",
  metric_conversion: "Convert between metric units",
  metric_imperial_conversion: "Convert between metric and imperial units",
  metric_and_imperial_conversion: "Convert between metric and imperial units",
  imperial_to_metric_length_area: "Convert imperial lengths to metric",
  imperial_to_metric_volume: "Convert imperial volumes to metric",
  multi_step_conversion: "Convert units in multiple steps",
  multi_step_conversions: "Convert units in multiple steps",
  temperature_conversion_rule: "Convert between temperature scales",
  temperature_conversion: "Convert between temperature scales",
  imperial_metric_conversion: "Convert between imperial and metric units",
  capacity: "Work with capacity and liquid measures",
  volume: "Calculate volumes",
  volume_multiplication: "Multiply to find volumes",
  volume_subtraction: "Subtract volumes",
  volume_scaling: "Scale volumes up or down",
  volume_scaling_of_a_cube: "Scale the volume of a cube",
  volume_scaling_of_a_cuboid: "Scale the volume of a cuboid",
  volume_and_scaling: "Work with volume and scaling",
  volume_surface_area: "Calculate volume and surface area",
  reverse_volume_scaling: "Work backwards from a scaled volume",
  area_and_volume_scaling: "Scale areas and volumes together",
  multi_step_volume_problem: "Solve volume problems with multiple steps",
  division_with_remainder_volume: "Divide volumes and find remainders",
  finding_a_fraction_of_a_volume: "Find a fraction of a volume",
  liquid_volume_calculation: "Calculate liquid volumes",
  speed_distance_time: "Calculate speed, distance and time",
  average_speed: "Work out average speed",
  scale_and_speed: "Use scales to work out speed",
  area_and_perimeter: "Calculate area and perimeter",
  area_and_scaling: "Scale areas up or down",
  multi_step_measurement: "Solve measurement problems with multiple steps",
  proportional_reasoning: "Use proportional reasoning with measurements",
  // Geometry
  area_and_subtraction: "Find areas by subtracting shapes",
  area_and_unit_conversion: "Calculate area with unit conversions",
  area_of_a_triangle: "Calculate the area of a triangle",
  area_of_composite_shapes: "Find areas of composite shapes",
  area_and_borders: "Calculate areas including borders",
  circles_and_perimeter: "Work with circles and perimeter",
  complex_area: "Calculate areas of complex shapes",
  composite_area: "Find areas of composite shapes",
  fractional_area: "Find fractional parts of areas",
  fractional_shading: "Work out what fraction is shaded",
  percentage_area: "Find percentage of an area",
  percentages_and_area: "Use percentages with areas",
  perimeter_and_cost: "Calculate perimeter and cost",
  perimeter_of_composite_shapes: "Find perimeters of composite shapes",
  scale_drawings: "Work with scale drawings",
  "3d_area_volume": "Calculate 3D areas and volumes",
  "3d_packing": "Pack shapes into 3D spaces",
  "3d_surface_area": "Calculate 3D surface areas",
  "3d_views_and_surface_area": "Work with 3D views and surface area",
  "3d_visualisation": "Visualise 3D shapes",
  "3d_volume": "Calculate 3D volumes",
  compound_3d_volume: "Find volumes of compound 3D shapes",
  cutting_cubes: "Work out results of cutting cubes",
  multi_step_3d_geometry: "Solve 3D geometry in multiple steps",
  nets_of_3d_shapes: "Work with nets of 3D shapes",
  packing_cubes: "Pack cubes into spaces",
  surface_area: "Calculate surface area",
  surface_area_and_cost: "Calculate surface area and cost",
  surface_area_of_cuboids: "Find the surface area of cuboids",
  volume_and_conversion: "Calculate volume with conversions",
  volume_and_packing: "Work with volume and packing",
  volume_of_a_cuboid: "Calculate the volume of a cuboid",
  volume_of_composite_shapes: "Find volumes of composite shapes",
  tiling: "Work out how tiles fit in a space",
  tiling_and_cost: "Calculate tiling and cost",
  tiling_and_percentages: "Work with tiling and percentages",
  tiling_and_proportions: "Use proportions when tiling",
  tiling_with_a_border: "Calculate tiling with a border",
  tiling_with_borders: "Calculate tiling with borders",
  tiling_packing: "Work out tiling and packing problems",
  shape_nesting: "Work with nested shapes",
  shape_nesting_and_area: "Find areas of nested shapes",
  shape_nesting_and_percentages: "Use percentages with nested shapes",
  clock_angles: "Calculate angles on a clock face",
  angles_and_time: "Work with angles and time",
  angles_on_a_line: "Find missing angles on a line",
  cartesian_coordinates: "Plot and read coordinates",
  algebraic_geometry: "Solve geometry problems with algebra",
  // Percentages
  basic_percentage_calculation: "Calculate basic percentages",
  percentage_increase: "Calculate percentage increases",
  percentage_decrease: "Calculate percentage decreases",
  percentage_of_a_quantity: "Find a percentage of a quantity",
  percentage_of_a_percentage: "Find a percentage of a percentage",
  percentage_of_a_remainder: "Find a percentage of a remainder",
  remaining_percentage: "Work out the remaining percentage",
  percentage_and_fraction_conversion: "Convert between percentages and fractions",
  percentage_fraction_conversion: "Convert between percentages and fractions",
  percentage_change_and_fractions: "Percentage changes with fractions",
  percentage_change_and_new_fraction: "Find new fractions after percentage changes",
  reverse_percentage: "Work backwards from a percentage",
  reverse_percentages: "Work backwards from percentages",
  reverse_percentages_discount: "Find original price before a discount",
  reverse_percentages_loss: "Find original value before a loss",
  reverse_percentages_profit: "Find original value before a profit",
  reverse_percentages_vat: "Find the price before VAT",
  reverse_percentage_and_change: "Reverse percentage with changes",
  reverse_percentage_change: "Find the original after a percentage change",
  reverse_percentage_logic: "Use logic to reverse percentages",
  reverse_percentage_smallest_number: "Find the smallest number using reverse percentages",
  reverse_percentage_and_sequential_change: "Reverse sequential percentage changes",
  reverse_area_percentages: "Reverse percentage calculations with area",
  reverse_demographic_percentages: "Reverse percentage calculations with demographics",
  reverse_spatial_percentages: "Reverse percentage calculations with space",
  compound_percentages: "Calculate compound percentages",
  compound_percentages_remainder: "Compound percentages with remainders",
  compound_set_percentages: "Work with compound set percentages",
  sequential_percentages: "Apply percentages in sequence",
  sequential_percentage_change: "Apply percentage changes in sequence",
  sequential_percentage_logic: "Use logic with sequential percentages",
  sequential_percentage_removal: "Remove percentages in sequence",
  sequential_change_and_final_percentage: "Find the final percentage after changes",
  financial_logic: "Solve financial problems with percentages",
  sequential_financial_logic: "Solve multi-step financial percentage problems",
  multi_step_percentages: "Solve percentage problems with multiple steps",
  multi_step_percentage_calculation: "Multi-step percentage calculations",
  multi_step_percentage_and_units: "Multi-step percentages with unit conversions",
  // Algebra
  linear_progression: "Continue a number pattern step by step",
  linear_intersection: "Find where two number patterns meet",
  disguised_algebra: "Solve algebra problems hidden in words",
  grouped_variable_sums: "Add up groups of unknowns",
  associated_properties: "Use linked properties to find values",
  associated_property_logic: "Use logic with linked properties",
  simultaneous_equations: "Solve two equations at the same time",
  simultaneous_equations_disguised: "Solve hidden simultaneous equations",
  simultaneous_logic: "Use logic to solve simultaneous problems",
  multi_variable_algebra: "Solve problems with multiple unknowns",
  multi_variable_ratio: "Work with ratios involving multiple unknowns",
  multi_variable_ratio_constraints: "Solve ratio problems with constraints",
  multi_variable_ratios: "Work with multiple ratios together",
  logic_puzzle: "Solve a logic puzzle using algebra",
  // Probability & Statistics
  qualitative_likelihood: "Judge how likely events are",
  expected_frequency: "Work out how often something should happen",
  complementary_fractions: "Find the probability of something not happening",
  probability_from_a_set: "Find probability from a set of items",
  sample_space_counting: "Count all possible outcomes",
  sample_space_combined_probability: "Find combined probability from a sample space",
  sample_space_without_replacement: "Find probability when items aren't replaced",
  combined_statistics_probability: "Use statistics and probability together",
  changing_probability: "Work out how probability changes",
  // English SPAG
  identifying_word_classes: "Pick out nouns, verbs and adjectives in a sentence",
  identifying_word_classes_pronouns: "Find the pronoun in a sentence",
  identifying_word_classes_determiners: "Find the determiner in a sentence",
  identifying_word_classes_adverbs: "Find the adverb in a sentence",
  identifying_word_classes_determiners_pronouns_adverbs: "Identify determiners, pronouns and adverbs",
  word_classes: "Identify different word classes",
  word_classes_pronouns: "Find the pronoun in a sentence",
  word_classes_determiners: "Find the determiner in a sentence",
  word_classes_adverbs: "Find the adverb in a sentence",
  "word_classes:_pronouns": "Find the pronoun in a sentence",
  "word_classes:_determiners": "Find the determiner in a sentence",
  "word_classes:_adverbs": "Find the adverb in a sentence",
  prefix_meanings: "Work out what a prefix means",
  prefix_meanings_anti_mis_re_sub: "Understand anti-, mis-, re- and sub- prefixes",
  prefix_meanings_re_sub: "Understand re- and sub- prefixes",
  prefix_meanings_mis: "Understand the mis- prefix",
  prefix_meanings_anti: "Understand the anti- prefix",
  prefix_meanings_sub: "Understand the sub- prefix",
  prefixes: "Identify and understand prefixes",
  suffix_application: "Add the right suffix to complete a word",
  suffix_application_ate_ise_ify_ment: "Choose from -ate, -ise, -ify or -ment",
  suffix_application_ment: "Add the suffix -ment to complete a word",
  suffix_application_ate_ise_ify: "Choose from -ate, -ise or -ify",
  suffix_application_ise_ify_ate_ment: "Choose the right suffix to complete a word",
  suffix_application_ify: "Add the suffix -ify to complete a word",
  synonyms_and_antonyms: "Find words with similar or opposite meanings",
  formal_vs_informal_vocabulary: "Choose formal or informal words",
  formal_vs_informal: "Tell apart formal and informal writing",
  formal_and_informal_vocabulary: "Choose the right level of formality",
  relative_clauses_and_relative_pronouns: "Spot relative clauses and pronouns",
  relative_clauses: "Identify relative clauses in sentences",
  relative_pronouns: "Find relative pronouns like who, which, that",
  subordinate_vs_main_clauses: "Tell apart main and subordinate clauses",
  main_clauses: "Find the main clause in a sentence",
  subordinate_clauses: "Find the subordinate clause in a sentence",
  colons_and_semi_colons_in_lists_or_boundary_sentences: "Use colons and semi-colons correctly",
  colons_and_semi_colons: "Use colons and semi-colons in sentences",
  colons_in_lists: "Use colons to introduce lists",
  colons_and_semi_colons_in_lists: "Use colons and semi-colons in lists",
  semi_colons_in_lists: "Use semi-colons in lists",
  semi_colons: "Use semi-colons between clauses",
  dashes_and_hyphens_for_clarity: "Use dashes and hyphens to add clarity",
  dashes_for_clarity: "Use dashes to add extra information",
  dashes_and_hyphens: "Use dashes and hyphens correctly",
  hyphens_for_clarity: "Use hyphens to make meaning clearer",
  possessive_apostrophes_plural: "Add apostrophes for plural possession",
  possessive_apostrophes_singular_vs_plural: "Choose singular or plural possessive apostrophes",
  possessive_apostrophes: "Add apostrophes to show belonging",
  possessive_apostrophes_singular: "Add apostrophes for singular possession",
  modal_verbs_for_possibility_or_obligation: "Identify modal verbs for possibility or obligation",
  modal_verbs_for_obligation: "Find the modal verb showing obligation",
  modal_verbs_for_possibility: "Find the modal verb showing possibility",
  modal_verbs_possibility: "Find the modal verb showing possibility",
  modal_verbs: "Identify modal verbs in sentences",
  passive_and_active_voice_transformation: "Change between active and passive voice",
  passive_and_active_voice: "Understand active and passive voice",
  passive_to_active_voice_transformation: "Change passive voice to active voice",
  active_to_passive_voice_transformation: "Change active voice to passive voice",
  active_and_passive_voice: "Tell apart active and passive voice",
  the_subjunctive_mood: "Use the subjunctive mood correctly",
  fronted_adverbials_and_comma_placement: "Use fronted adverbials with commas",
};

/** Display-friendly question type names */
export const QUESTION_TYPE_DISPLAY_NAMES: Record<string, string> = {
  missing_number_equations: "Missing Number Equations",
  number_codes: "Number Codes",
  word_completion: "Word Completion",
  logic_puzzles: "Logic Puzzles",
  letter_equations: "Letter Equations",
  synonyms: "Synonyms",
  three_letter_completion: "Three-Letter Completion",
  letter_pairs: "Letter Pairs",
  analogies: "Analogies",
  hidden_words: "Hidden Words",
  letter_completion: "Missing Letters",
  letter_completion_double: "Missing Letters (Double)",
  sentence_completion: "Sentence Completion",
  alphabet_series: "Alphabet Series",
  antonyms: "Antonyms",
  number_patterns: "Number Patterns",
  odd_one_out: "Odd One Out",
  opposite_meaning: "Opposite Meaning",
  similar_meaning: "Similar Meaning",
  compound_words: "Compound Words",
  alphabetical_order: "Alphabetical Order",
  word_ladder: "Word Ladder",
  word_swap: "Word Swap",
  anagram: "Anagram",
  move_a_letter: "Move A Letter",
  forming_new_words: "Forming New Words",
  four_letter_completion: "Four-Letter Completion",
  multiple_meanings: "Multiple Meanings",
  missing_letters: "Missing Letters",
  letter_word_codes: "Letter Word Codes",
  sentence_completion_analogies: "Sentence Completion Analogies",
  comprehension: "Comprehension",
  letter_sequences: "Letter Sequences",
  // Maths - Fractions
  fraction_of_an_amount: "Fraction of an Amount",
  fraction_of_an_amount_discount: "Fraction of an Amount (Discount)",
  fraction_of_an_amount_money: "Fraction of an Amount (Money)",
  fraction_of_an_amount_remainder: "Fraction of an Amount (Remainder)",
  fraction_of_an_amount_spending: "Fraction of an Amount (Spending)",
  reverse_fraction_of_an_amount: "Reverse Fraction",
  fractions_of_mixed_amounts: "Fractions of Mixed Amounts",
  discrete_grouping: "Discrete Grouping",
  discrete_grouping_with_remainder: "Discrete Grouping (Remainder)",
  fraction_of_a_mixed_number: "Fraction of a Mixed Number",
  fraction_of_a_mixed_number_remainder: "Fraction of a Mixed Number (Remainder)",
  mixed_numbers_and_fractions_of_amounts: "Mixed Numbers & Fractions",
  mixed_numbers_with_money: "Mixed Numbers with Money",
  dividing_a_mixed_number_by_a_fraction: "Dividing Mixed Number by Fraction",
  dividing_a_mixed_number_by_an_integer: "Dividing Mixed Number by Integer",
  pure_mixed_arithmetic: "Mixed Number Arithmetic",
  fractions_and_decimals: "Fractions & Decimals",
  fractions_and_percentages: "Fractions & Percentages",
  multi_step_fraction_calculation: "Multi-Step Fraction Calculation",
  multi_step_fraction_problem: "Multi-Step Fraction Problem",
  multi_step_fractions_of_amounts: "Multi-Step Fractions of Amounts",
  multi_step_discounts: "Multi-Step Discounts",
  sequential_remainder_fractions: "Sequential Remainder Fractions",
  sequential_remainder_fractions_working_backwards: "Sequential Remainders (Working Backwards)",
  sequential_remainder_fractions_as_a_fraction: "Sequential Remainders (as Fraction)",
  fraction_of_an_amount_discounts: "Fraction of an Amount (Discounts)",
  fraction_of_an_amount_finding_remainder: "Fraction of an Amount (Finding Remainder)",
  fraction_of_an_amount_working_backwards: "Fraction of an Amount (Working Backwards)",
  fraction_of_amount_with_conversion: "Fraction of Amount (Conversion)",
  finding_the_whole_from_a_part: "Finding the Whole from a Part",
  fraction_of_a_fraction: "Fraction of a Fraction",
  multiplying_fractions: "Multiplying Fractions",
  comparing_fractions: "Comparing Fractions",
  comparing_fractions_with_conversion: "Comparing Fractions (Conversion)",
  fractions_and_money: "Fractions & Money",
  fractions_and_time: "Fractions & Time",
  fractions_and_ratios: "Fractions & Ratios",
  multi_step_discrete_grouping: "Multi-Step Discrete Grouping",
  mixed_numbers: "Mixed Numbers",
  mixed_numbers_and_money: "Mixed Numbers & Money",
  mixed_numbers_and_distance: "Mixed Numbers & Distance",
  mixed_numbers_and_division: "Mixed Numbers (Division)",
  mixed_numbers_and_multiplication: "Mixed Numbers (Multiplication)",
  mixed_numbers_and_unit_conversion: "Mixed Numbers (Unit Conversion)",
  mixed_numbers_and_volumes: "Mixed Numbers & Volumes",
  mixed_numbers_units: "Mixed Numbers & Units",
  distance_and_mixed_numbers: "Distance & Mixed Numbers",
  fractions_with_mixed_numbers: "Fractions with Mixed Numbers",
  adding_mixed_numbers: "Adding Mixed Numbers",
  subtracting_mixed_numbers: "Subtracting Mixed Numbers",
  pure_mixed_arithmetic_division: "Mixed Arithmetic (Division)",
  pure_mixed_arithmetic_money: "Mixed Arithmetic (Money)",
  pure_mixed_arithmetic_multiplication: "Mixed Arithmetic (Multiplication)",
  mixed_arithmetic: "Mixed Arithmetic",
  mixed_number_arithmetic: "Mixed Number Arithmetic",
  mixed_numbers_arithmetic: "Mixed Numbers Arithmetic",
  multi_step_fractions: "Multi-Step Fractions",
  multi_step_problem: "Multi-Step Problem",
  multi_step_problem_solving: "Multi-Step Problem Solving",
  sequential_fractions_addition: "Sequential Fractions (Addition)",
  sequential_fractions_of_original: "Sequential Fractions (of Original)",
  sequential_remainder: "Sequential Remainder",
  sequential_remainder_working_backwards: "Sequential Remainder (Working Backwards)",
  working_backwards: "Working Backwards",
  working_backwards_with_fractions: "Working Backwards (Fractions)",
  linguistic_parsing: "Linguistic Parsing",
  linguistic_parsing_comparison: "Linguistic Parsing (Comparison)",
  linguistic_parsing_difference: "Linguistic Parsing (Difference)",
  linguistic_parsing_and_addition: "Linguistic Parsing (Addition)",
  linguistic_parsing_with_fractions: "Linguistic Parsing (Fractions)",
  // Measurements
  reading_a_scale: "Reading a Scale",
  reading_mass_scales: "Reading Mass Scales",
  reading_volume_scales: "Reading Volume Scales",
  reading_scales_mass: "Reading Scales (Mass)",
  reading_scales_volume: "Reading Scales (Volume)",
  scale_reading: "Scale Reading",
  time_calculation: "Time Calculation",
  time_conversion: "Time Conversion",
  time_conversions: "Time Conversions",
  time_and_rate: "Time & Rate",
  timetable_calculation: "Timetable Calculation",
  timetable_interpretation: "Timetable Interpretation",
  multi_step_time_calculation: "Multi-Step Time Calculation",
  converting_decimal_hours_to_minutes: "Decimal Hours to Minutes",
  converting_decimal_minutes_to_seconds: "Decimal Minutes to Seconds",
  working_backwards_with_time: "Working Backwards (Time)",
  unit_conversion: "Unit Conversion",
  metric_conversion: "Metric Conversion",
  metric_imperial_conversion: "Metric & Imperial Conversion",
  metric_and_imperial_conversion: "Metric & Imperial Conversion",
  imperial_to_metric_length_area: "Imperial to Metric (Length/Area)",
  imperial_to_metric_volume: "Imperial to Metric (Volume)",
  multi_step_conversion: "Multi-Step Conversion",
  multi_step_conversions: "Multi-Step Conversions",
  temperature_conversion_rule: "Temperature Conversion",
  temperature_conversion: "Temperature Conversion",
  imperial_metric_conversion: "Imperial & Metric Conversion",
  capacity: "Capacity",
  volume: "Volume",
  volume_multiplication: "Volume Multiplication",
  volume_subtraction: "Volume Subtraction",
  volume_scaling: "Volume Scaling",
  volume_scaling_of_a_cube: "Volume Scaling (Cube)",
  volume_scaling_of_a_cuboid: "Volume Scaling (Cuboid)",
  volume_and_scaling: "Volume & Scaling",
  volume_surface_area: "Volume & Surface Area",
  reverse_volume_scaling: "Reverse Volume Scaling",
  area_and_volume_scaling: "Area & Volume Scaling",
  multi_step_volume_problem: "Multi-Step Volume Problem",
  division_with_remainder_volume: "Division with Remainder (Volume)",
  finding_a_fraction_of_a_volume: "Fraction of a Volume",
  liquid_volume_calculation: "Liquid Volume Calculation",
  speed_distance_time: "Speed, Distance & Time",
  average_speed: "Average Speed",
  scale_and_speed: "Scale & Speed",
  area_and_scaling: "Area & Scaling",
  multi_step_measurement: "Multi-Step Measurement",
  proportional_reasoning: "Proportional Reasoning",
  // Geometry
  area_and_subtraction: "Area & Subtraction",
  area_and_unit_conversion: "Area & Unit Conversion",
  area_of_a_triangle: "Area of a Triangle",
  area_of_composite_shapes: "Area of Composite Shapes",
  area_and_borders: "Area & Borders",
  circles_and_perimeter: "Circles & Perimeter",
  complex_area: "Complex Area",
  composite_area: "Composite Area",
  fractional_area: "Fractional Area",
  fractional_shading: "Fractional Shading",
  percentage_area: "Percentage Area",
  percentages_and_area: "Percentages & Area",
  perimeter_and_cost: "Perimeter & Cost",
  perimeter_of_composite_shapes: "Perimeter of Composite Shapes",
  scale_drawings: "Scale Drawings",
  "3d_area_volume": "3D Area & Volume",
  "3d_packing": "3D Packing",
  "3d_surface_area": "3D Surface Area",
  "3d_views_and_surface_area": "3D Views & Surface Area",
  "3d_visualisation": "3D Visualisation",
  "3d_volume": "3D Volume",
  compound_3d_volume: "Compound 3D Volume",
  cutting_cubes: "Cutting Cubes",
  multi_step_3d_geometry: "Multi-Step 3D Geometry",
  nets_of_3d_shapes: "Nets of 3D Shapes",
  packing_cubes: "Packing Cubes",
  surface_area: "Surface Area",
  surface_area_and_cost: "Surface Area & Cost",
  surface_area_of_cuboids: "Surface Area of Cuboids",
  volume_and_conversion: "Volume & Conversion",
  volume_and_packing: "Volume & Packing",
  volume_of_a_cuboid: "Volume of a Cuboid",
  volume_of_composite_shapes: "Volume of Composite Shapes",
  tiling: "Tiling",
  tiling_and_cost: "Tiling & Cost",
  tiling_and_percentages: "Tiling & Percentages",
  tiling_and_proportions: "Tiling & Proportions",
  tiling_with_a_border: "Tiling with a Border",
  tiling_with_borders: "Tiling with Borders",
  tiling_packing: "Tiling & Packing",
  shape_nesting: "Shape Nesting",
  shape_nesting_and_area: "Shape Nesting & Area",
  shape_nesting_and_percentages: "Shape Nesting & Percentages",
  clock_angles: "Clock Angles",
  angles_and_time: "Angles & Time",
  angles_on_a_line: "Angles on a Line",
  cartesian_coordinates: "Cartesian Coordinates",
  algebraic_geometry: "Algebraic Geometry",
  // Percentages
  basic_percentage_calculation: "Basic Percentage Calculation",
  percentage_increase: "Percentage Increase",
  percentage_decrease: "Percentage Decrease",
  percentage_of_a_quantity: "Percentage of a Quantity",
  percentage_of_a_percentage: "Percentage of a Percentage",
  percentage_of_a_remainder: "Percentage of a Remainder",
  remaining_percentage: "Remaining Percentage",
  percentage_and_fraction_conversion: "Percentage & Fraction Conversion",
  percentage_fraction_conversion: "Percentage & Fraction Conversion",
  percentage_change_and_fractions: "Percentage Change & Fractions",
  percentage_change_and_new_fraction: "Percentage Change & New Fraction",
  reverse_percentage: "Reverse Percentage",
  reverse_percentages: "Reverse Percentages",
  reverse_percentages_discount: "Reverse Percentages (Discount)",
  reverse_percentages_loss: "Reverse Percentages (Loss)",
  reverse_percentages_profit: "Reverse Percentages (Profit)",
  reverse_percentages_vat: "Reverse Percentages (VAT)",
  reverse_percentage_and_change: "Reverse Percentage & Change",
  reverse_percentage_change: "Reverse Percentage Change",
  reverse_percentage_logic: "Reverse Percentage Logic",
  reverse_percentage_smallest_number: "Reverse Percentage (Smallest Number)",
  reverse_percentage_and_sequential_change: "Reverse Sequential Percentage Change",
  reverse_area_percentages: "Reverse Area Percentages",
  reverse_demographic_percentages: "Reverse Demographic Percentages",
  reverse_spatial_percentages: "Reverse Spatial Percentages",
  compound_percentages: "Compound Percentages",
  compound_percentages_remainder: "Compound Percentages (Remainder)",
  compound_set_percentages: "Compound Set Percentages",
  sequential_percentages: "Sequential Percentages",
  sequential_percentage_change: "Sequential Percentage Change",
  sequential_percentage_logic: "Sequential Percentage Logic",
  sequential_percentage_removal: "Sequential Percentage Removal",
  sequential_change_and_final_percentage: "Sequential Change & Final Percentage",
  financial_logic: "Financial Logic",
  sequential_financial_logic: "Sequential Financial Logic",
  multi_step_percentages: "Multi-Step Percentages",
  multi_step_percentage_calculation: "Multi-Step Percentage Calculation",
  multi_step_percentage_and_units: "Multi-Step Percentages & Units",
  // Algebra
  linear_progression: "Linear Progression",
  linear_intersection: "Linear Intersection",
  disguised_algebra: "Disguised Algebra",
  grouped_variable_sums: "Grouped Variable Sums",
  associated_properties: "Associated Properties",
  associated_property_logic: "Associated Property Logic",
  simultaneous_equations: "Simultaneous Equations",
  simultaneous_equations_disguised: "Simultaneous Equations (Disguised)",
  simultaneous_logic: "Simultaneous Logic",
  multi_variable_algebra: "Multi-Variable Algebra",
  multi_variable_ratio: "Multi-Variable Ratio",
  multi_variable_ratio_constraints: "Multi-Variable Ratio (Constraints)",
  multi_variable_ratios: "Multi-Variable Ratios",
  logic_puzzle: "Logic Puzzle",
  // Probability & Statistics
  qualitative_likelihood: "Qualitative Likelihood",
  expected_frequency: "Expected Frequency",
  complementary_fractions: "Complementary Fractions",
  probability_from_a_set: "Probability from a Set",
  sample_space_counting: "Sample Space Counting",
  sample_space_combined_probability: "Sample Space (Combined Probability)",
  sample_space_without_replacement: "Sample Space (Without Replacement)",
  combined_statistics_probability: "Combined Statistics & Probability",
  changing_probability: "Changing Probability",
  // English SPAG
  identifying_word_classes: "Identifying Word Classes",
  identifying_word_classes_pronouns: "Word Classes (Pronouns)",
  identifying_word_classes_determiners: "Word Classes (Determiners)",
  identifying_word_classes_adverbs: "Word Classes (Adverbs)",
  identifying_word_classes_determiners_pronouns_adverbs: "Word Classes (Mixed)",
  word_classes: "Word Classes",
  word_classes_pronouns: "Word Classes (Pronouns)",
  word_classes_determiners: "Word Classes (Determiners)",
  word_classes_adverbs: "Word Classes (Adverbs)",
  prefix_meanings: "Prefix Meanings",
  prefix_meanings_anti_mis_re_sub: "Prefix Meanings (anti, mis, re, sub)",
  prefix_meanings_re_sub: "Prefix Meanings (re, sub)",
  prefix_meanings_mis: "Prefix Meanings (mis)",
  prefix_meanings_anti: "Prefix Meanings (anti)",
  prefix_meanings_sub: "Prefix Meanings (sub)",
  prefixes: "Prefixes",
  suffix_application: "Suffix Application",
  suffix_application_ate_ise_ify_ment: "Suffix Application (ate, ise, ify, ment)",
  suffix_application_ment: "Suffix Application (ment)",
  suffix_application_ate_ise_ify: "Suffix Application (ate, ise, ify)",
  suffix_application_ise_ify_ate_ment: "Suffix Application (ise, ify, ate, ment)",
  suffix_application_ify: "Suffix Application (ify)",
  synonyms_and_antonyms: "Synonyms & Antonyms",
  formal_vs_informal_vocabulary: "Formal vs Informal Vocabulary",
  formal_vs_informal: "Formal vs Informal",
  formal_and_informal_vocabulary: "Formal & Informal Vocabulary",
  relative_clauses_and_relative_pronouns: "Relative Clauses & Pronouns",
  relative_clauses: "Relative Clauses",
  relative_pronouns: "Relative Pronouns",
  subordinate_vs_main_clauses: "Subordinate vs Main Clauses",
  main_clauses: "Main Clauses",
  subordinate_clauses: "Subordinate Clauses",
  colons_and_semi_colons_in_lists_or_boundary_sentences: "Colons & Semi-colons (Lists/Sentences)",
  colons_and_semi_colons: "Colons & Semi-colons",
  colons_in_lists: "Colons in Lists",
  colons_and_semi_colons_in_lists: "Colons & Semi-colons in Lists",
  semi_colons_in_lists: "Semi-colons in Lists",
  semi_colons: "Semi-colons",
  dashes_and_hyphens_for_clarity: "Dashes & Hyphens for Clarity",
  dashes_for_clarity: "Dashes for Clarity",
  dashes_and_hyphens: "Dashes & Hyphens",
  hyphens_for_clarity: "Hyphens for Clarity",
  possessive_apostrophes_plural: "Possessive Apostrophes (Plural)",
  possessive_apostrophes_singular_vs_plural: "Possessive Apostrophes (Singular vs Plural)",
  possessive_apostrophes: "Possessive Apostrophes",
  possessive_apostrophes_singular: "Possessive Apostrophes (Singular)",
  modal_verbs_for_possibility_or_obligation: "Modal Verbs (Possibility/Obligation)",
  modal_verbs_for_obligation: "Modal Verbs (Obligation)",
  modal_verbs_for_possibility: "Modal Verbs (Possibility)",
  modal_verbs_possibility: "Modal Verbs (Possibility)",
  modal_verbs: "Modal Verbs",
  passive_and_active_voice_transformation: "Active & Passive Voice Transformation",
  passive_and_active_voice: "Passive & Active Voice",
  passive_to_active_voice_transformation: "Passive to Active Voice",
  active_to_passive_voice_transformation: "Active to Passive Voice",
  active_and_passive_voice: "Active & Passive Voice",
  the_subjunctive_mood: "The Subjunctive Mood",
  fronted_adverbials_and_comma_placement: "Fronted Adverbials & Comma Placement",
};

export function formatQuestionType(qType: string): string {
  return (
    QUESTION_TYPE_DISPLAY_NAMES[qType] ||
    qType
      .replace(/_/g, " ")
      .replace(/\b\w/g, (c) => c.toUpperCase())
  );
}

/** Exam board display metadata */
export const EXAM_BOARD_META: Record<
  string,
  { name: string; subtitle: string; icon: string }
> = {
  GL: {
    name: "GL Assessment",
    subtitle: "Official-style GL practice by topic",
    icon: "GraduationCap",
  },
  CEM: {
    name: "CEM Practice",
    subtitle: "Practice for CEM-style questions",
    icon: "Brain",
  },
  ISEB: {
    name: "ISEB Practice",
    subtitle: "Practice for ISEB pre-test questions",
    icon: "ClipboardList",
  },
  Generic: {
    name: "General Practice",
    subtitle: "Mixed-topic practice across all boards",
    icon: "BookOpen",
  },
};
