import type { PrismaClient } from "../src/generated/prisma/client.ts";

/**
 * GL Assessment Verbal Reasoning Questions for Ages 7-8
 * 4 question types × 10 questions each = 40 questions (starter set)
 *
 * Question types: synonyms, antonyms, word_completion, odd_one_out
 * Difficulty distribution: 50% easy (2), 40% medium (3), 10% hard (4)
 */

export async function seedGLVerbal78(prisma: PrismaClient) {
  const questions = [
    // Synonyms (10 questions, easier for younger kids)
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'happy'?",
      options: ["sad", "joyful", "angry", "tired"],
      correctAnswer: 1,
      explanation: "'Joyful' means feeling very happy.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'big'?",
      options: ["small", "large", "tiny", "little"],
      correctAnswer: 1,
      explanation: "'Large' means the same as big.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'fast'?",
      options: ["slow", "quick", "tired", "lazy"],
      correctAnswer: 1,
      explanation: "'Quick' means moving or doing something fast.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'small'?",
      options: ["huge", "tiny", "big", "giant"],
      correctAnswer: 1,
      explanation: "'Tiny' means very small.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'nice'?",
      options: ["mean", "kind", "bad", "rude"],
      correctAnswer: 1,
      explanation: "'Kind' means being nice to others.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'cold'?",
      options: ["hot", "chilly", "warm", "sunny"],
      correctAnswer: 1,
      explanation: "'Chilly' means feeling cold.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'brave'?",
      options: ["scared", "fearless", "afraid", "worried"],
      correctAnswer: 1,
      explanation: "'Fearless' means being very brave.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'funny'?",
      options: ["sad", "amusing", "boring", "serious"],
      correctAnswer: 1,
      explanation: "'Amusing' means something that makes you laugh or smile.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'loud'?",
      options: ["quiet", "noisy", "silent", "soft"],
      correctAnswer: 1,
      explanation: "'Noisy' means making a lot of loud sounds.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'smart'?",
      options: ["silly", "clever", "foolish", "dumb"],
      correctAnswer: 1,
      explanation: "'Clever' means being smart and quick to learn.",
      difficulty: 2,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "7-8",
      examBoard: "GL",
    },

    // Antonyms (10 questions)
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hot'?",
      options: ["warm", "cold", "sunny", "bright"],
      correctAnswer: 1,
      explanation: "'Cold' is the opposite of hot.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'up'?",
      options: ["over", "down", "high", "top"],
      correctAnswer: 1,
      explanation: "'Down' is the opposite of up.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'day'?",
      options: ["morning", "night", "afternoon", "evening"],
      correctAnswer: 1,
      explanation: "'Night' is the opposite of day.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'happy'?",
      options: ["joyful", "sad", "cheerful", "glad"],
      correctAnswer: 1,
      explanation: "'Sad' is the opposite of happy.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'wet'?",
      options: ["damp", "dry", "moist", "soggy"],
      correctAnswer: 1,
      explanation: "'Dry' is the opposite of wet.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'old'?",
      options: ["ancient", "young", "aged", "elderly"],
      correctAnswer: 1,
      explanation: "'Young' is the opposite of old.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'loud'?",
      options: ["noisy", "quiet", "deafening", "booming"],
      correctAnswer: 1,
      explanation: "'Quiet' is the opposite of loud.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hard'?",
      options: ["tough", "soft", "solid", "firm"],
      correctAnswer: 1,
      explanation: "'Soft' is the opposite of hard.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'full'?",
      options: ["packed", "empty", "stuffed", "complete"],
      correctAnswer: 1,
      explanation: "'Empty' is the opposite of full.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'early'?",
      options: ["soon", "late", "prompt", "quick"],
      correctAnswer: 1,
      explanation: "'Late' is the opposite of early.",
      difficulty: 2,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "7-8",
      examBoard: "GL",
    },

    // Word Completion (10 questions)
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: c_t",
      options: ["a", "o", "i", "u"],
      correctAnswer: 0,
      explanation: "The word is 'cat'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: d_g",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'dog'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: s_n",
      options: ["i", "a", "o", "u"],
      correctAnswer: 3,
      explanation: "The word is 'sun'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: b_ll",
      options: ["i", "e", "a", "o"],
      correctAnswer: 2,
      explanation: "The word is 'ball'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: tr_e",
      options: ["a", "e", "i", "u"],
      correctAnswer: 3,
      explanation: "The word is 'true'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_use",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'house'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fr_end",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'friend'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fl_wer",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'flower'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_ppy",
      options: ["a", "e", "i", "o"],
      correctAnswer: 0,
      explanation: "The word is 'happy'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: l_ght",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'light'.",
      difficulty: 2,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "7-8",
      examBoard: "GL",
    },

    // Odd One Out (10 questions)
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["cat", "dog", "table", "bird"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Table' is the odd one out because it's not an animal.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["red", "blue", "happy", "green"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Happy' is the odd one out because it's not a color.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["apple", "banana", "carrot", "orange"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Carrot' is the odd one out because it's a vegetable, not a fruit.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["run", "jump", "sleep", "hop"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Sleep' is the odd one out because it's not an active movement.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["Monday", "Tuesday", "January", "Friday"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'January' is the odd one out because it's a month, not a day of the week.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["car", "bus", "train", "pencil"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Pencil' is the odd one out because it's not a vehicle.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["hat", "shoe", "sock", "shirt"],
      correctAnswer: 1,
      correctAnswers: [1],
      explanation: "'Shoe' is the odd one out because all others are worn in pairs except the hat.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["book", "pen", "computer", "eraser"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Computer' is the odd one out because it's electronic, while others are simple tools.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["circle", "square", "triangle", "purple"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Purple' is the odd one out because it's a color, not a shape.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["elephant", "mouse", "lion", "chair"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Chair' is the odd one out because it's not a living animal.",
      difficulty: 2,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "7-8",
      examBoard: "GL",
    },

    // Alphabet Series (10 questions: 4 same operations, 4 different operations, 2 mirror codes)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBC is to EF as HI is to ___",
      options: ["KL", "JK", "IJ", "LM"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "B to E is +3, C to F is +3. Both letters move forward by 3. H to K is +3, I to L is +3. So HI → KL.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nGJ is to KN as OR is to ___",
      options: ["SV", "QT", "PR", "TW"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "G to K is +4, J to N is +4. Both letters move forward by 4. O to S is +4, R to V is +4. So OR → SV.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nLP is to NR as TW is to ___",
      options: ["VY", "UX", "RU", "WZ"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "L to N is +2, P to R is +2. Both letters move forward by 2. T to V is +2, W to Y is +2. So TW → VY.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nRT is to VX as BD is to ___",
      options: ["FH", "EG", "CE", "GI"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "R to V is +4, T to X is +4. Both letters move forward by 4. B to F is +4, D to H is +4. So BD → FH.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nCE is to FK as MO is to ___",
      options: ["PU", "SU", "QS", "TU"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "C to F is +3, E to K is +6. First letter moves forward 3, second letter moves forward 6. M to P is +3, O to U is +6. So MO → PU.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nHM is to JQ as PS is to ___",
      options: ["RW", "QU", "SW", "TV"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "H to J is +2, M to Q is +4. First letter moves forward 2, second letter moves forward 4. P to R is +2, S to W is +4. So PS → RW.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nNP is to RU as DF is to ___",
      options: ["HK", "GJ", "IK", "EI"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "N to R is +4, P to U is +5. First letter moves forward 4, second letter moves forward 5. D to H is +4, F to K is +5. So DF → HK.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nSU is to WZ as AC is to ___",
      options: ["EH", "DF", "FI", "DG"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "S to W is +4, U to Z is +5. First letter moves forward 4, second letter moves forward 5. A to E is +4, C to H is +5. So AC → EH.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nEH is to VS as IM is to ___",
      options: ["RN", "QO", "SL", "PN"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. E (position 5) mirrors to V (position 22) because 27-5=22. H (position 8) mirrors to S (position 19) because 27-8=19. Similarly, I (position 9) mirrors to R (position 18) because 27-9=18, and M (position 13) mirrors to N (position 14) because 27-13=14. So IM → RN.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nJM is to QN as FI is to ___",
      options: ["UR", "TP", "UQ", "QT"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. J (position 10) mirrors to Q (position 17) because 27-10=17. M (position 13) mirrors to N (position 14) because 27-13=14. Similarly, F (position 6) mirrors to U (position 21) because 27-6=21, and I (position 9) mirrors to R (position 18) because 27-9=18. So FI → UR.",
      difficulty: 2,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "7-8",
      examBoard: "GL",
    },
  ];

  // Insert all questions
  for (const q of questions) {
    await prisma.question.create({ data: q });
  }

  console.log("✅ Seeded GL Verbal Reasoning Ages 7-8:", questions.length, "questions");
}
