import type { PrismaClient } from "../src/generated/prisma/client.ts";

/**
 * GL Assessment Verbal Reasoning Questions for Ages 6-7
 * 4 question types × 10 questions each = 40 questions (starter set)
 *
 * Question types: synonyms, antonyms, word_completion, odd_one_out
 * Difficulty distribution: 50% easy (2), 40% medium (3), 10% hard (4)
 */

export async function seedGLVerbal67(prisma: PrismaClient) {
  const questions = [
    // Synonyms (10 questions, easier for younger kids)
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'happy'?",
      options: ["sad", "joyful", "angry", "tired"],
      correctAnswer: 1,
      explanation: "'Joyful' means feeling very happy.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'big'?",
      options: ["small", "large", "tiny", "little"],
      correctAnswer: 1,
      explanation: "'Large' means the same as big.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'fast'?",
      options: ["slow", "quick", "tired", "lazy"],
      correctAnswer: 1,
      explanation: "'Quick' means moving or doing something fast.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'small'?",
      options: ["huge", "tiny", "big", "giant"],
      correctAnswer: 1,
      explanation: "'Tiny' means very small.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'nice'?",
      options: ["mean", "kind", "bad", "rude"],
      correctAnswer: 1,
      explanation: "'Kind' means being nice to others.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'cold'?",
      options: ["hot", "chilly", "warm", "sunny"],
      correctAnswer: 1,
      explanation: "'Chilly' means feeling cold.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'brave'?",
      options: ["scared", "fearless", "afraid", "worried"],
      correctAnswer: 1,
      explanation: "'Fearless' means being very brave.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'funny'?",
      options: ["sad", "amusing", "boring", "serious"],
      correctAnswer: 1,
      explanation: "'Amusing' means something that makes you laugh or smile.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'loud'?",
      options: ["quiet", "noisy", "silent", "soft"],
      correctAnswer: 1,
      explanation: "'Noisy' means making a lot of loud sounds.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'smart'?",
      options: ["silly", "clever", "foolish", "dumb"],
      correctAnswer: 1,
      explanation: "'Clever' means being smart and quick to learn.",
      difficulty: 1,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "6-7",
      examBoard: "GL",
    },

    // Antonyms (10 questions)
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hot'?",
      options: ["warm", "cold", "sunny", "bright"],
      correctAnswer: 1,
      explanation: "'Cold' is the opposite of hot.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'up'?",
      options: ["over", "down", "high", "top"],
      correctAnswer: 1,
      explanation: "'Down' is the opposite of up.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'day'?",
      options: ["morning", "night", "afternoon", "evening"],
      correctAnswer: 1,
      explanation: "'Night' is the opposite of day.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'happy'?",
      options: ["joyful", "sad", "cheerful", "glad"],
      correctAnswer: 1,
      explanation: "'Sad' is the opposite of happy.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'wet'?",
      options: ["damp", "dry", "moist", "soggy"],
      correctAnswer: 1,
      explanation: "'Dry' is the opposite of wet.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'old'?",
      options: ["ancient", "young", "aged", "elderly"],
      correctAnswer: 1,
      explanation: "'Young' is the opposite of old.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'loud'?",
      options: ["noisy", "quiet", "deafening", "booming"],
      correctAnswer: 1,
      explanation: "'Quiet' is the opposite of loud.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hard'?",
      options: ["tough", "soft", "solid", "firm"],
      correctAnswer: 1,
      explanation: "'Soft' is the opposite of hard.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'full'?",
      options: ["packed", "empty", "stuffed", "complete"],
      correctAnswer: 1,
      explanation: "'Empty' is the opposite of full.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'early'?",
      options: ["soon", "late", "prompt", "quick"],
      correctAnswer: 1,
      explanation: "'Late' is the opposite of early.",
      difficulty: 1,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "6-7",
      examBoard: "GL",
    },

    // Word Completion (10 questions)
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: c_t",
      options: ["a", "o", "i", "u"],
      correctAnswer: 0,
      explanation: "The word is 'cat'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: d_g",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'dog'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: s_n",
      options: ["i", "a", "o", "u"],
      correctAnswer: 3,
      explanation: "The word is 'sun'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: b_ll",
      options: ["i", "e", "a", "o"],
      correctAnswer: 2,
      explanation: "The word is 'ball'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: tr_e",
      options: ["a", "e", "i", "u"],
      correctAnswer: 3,
      explanation: "The word is 'true'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_use",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'house'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fr_end",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'friend'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fl_wer",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'flower'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_ppy",
      options: ["a", "e", "i", "o"],
      correctAnswer: 0,
      explanation: "The word is 'happy'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: l_ght",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'light'.",
      difficulty: 1,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "6-7",
      examBoard: "GL",
    },

    // Odd One Out (10 questions)
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["cat", "dog", "table", "bird"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Table' is the odd one out because it's not an animal.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["red", "blue", "happy", "green"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Happy' is the odd one out because it's not a color.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["apple", "banana", "carrot", "orange"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Carrot' is the odd one out because it's a vegetable, not a fruit.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["run", "jump", "sleep", "hop"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Sleep' is the odd one out because it's not an active movement.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["Monday", "Tuesday", "January", "Friday"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'January' is the odd one out because it's a month, not a day of the week.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["car", "bus", "train", "pencil"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Pencil' is the odd one out because it's not a vehicle.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["hat", "shoe", "sock", "shirt"],
      correctAnswer: 1,
      correctAnswers: [1],
      explanation: "'Shoe' is the odd one out because all others are worn in pairs except the hat.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["book", "pen", "computer", "eraser"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Computer' is the odd one out because it's electronic, while others are simple tools.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["circle", "square", "triangle", "purple"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Purple' is the odd one out because it's a color, not a shape.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["elephant", "mouse", "lion", "chair"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Chair' is the odd one out because it's not a living animal.",
      difficulty: 1,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "6-7",
      examBoard: "GL",
    },

    // Alphabet Series (10 questions: 6 same operations, 3 different operations, 1 mirror code)
    // Same operations (6 questions)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nAB is to DE as FG is to ___",
      options: ["IJ", "HI", "GH", "JK"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "A to D is +3, B to E is +3. Both letters move forward by 3. F to I is +3, G to J is +3. So FG → IJ.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nFH is to JL as NP is to ___",
      options: ["RT", "QS", "PR", "ST"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "F to J is +4, H to L is +4. Both letters move forward by 4. N to R is +4, P to T is +4. So NP → RT.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nCE is to HJ as LN is to ___",
      options: ["QS", "PR", "OP", "RS"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "C to H is +5, E to J is +5. Both letters move forward by 5. L to Q is +5, N to S is +5. So LN → QS.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nMO is to QS as TV is to ___",
      options: ["XZ", "WY", "UW", "YZ"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "M to Q is +4, O to S is +4. Both letters move forward by 4. T to X is +4, V to Z is +4. So TV → XZ.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nKN is to OR as SV is to ___",
      options: ["WZ", "VY", "XY", "UX"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "K to O is +4, N to R is +4. Both letters move forward by 4. S to W is +4, V to Z is +4. So SV → WZ.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nDG is to HK as IL is to ___",
      options: ["MP", "LO", "NO", "MN"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "D to H is +4, G to K is +4. Both letters move forward by 4. I to M is +4, L to P is +4. So IL → MP.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    // Different operations (3 questions)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBD is to EH as GI is to ___",
      options: ["JM", "KM", "IL", "HK"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "B to E is +3, D to H is +4. First letter moves forward 3, second letter moves forward 4. G to J is +3, I to M is +4. So GI → JM.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nFJ is to HN as KM is to ___",
      options: ["MQ", "NR", "LO", "MP"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "F to H is +2, J to N is +4. First letter moves forward 2, second letter moves forward 4. K to M is +2, M to Q is +4. So KM → MQ.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nLN is to OS as PR is to ___",
      options: ["SW", "RU", "TV", "SU"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "L to O is +3, N to S is +5. First letter moves forward 3, second letter moves forward 5. P to S is +3, R to W is +5. So PR → SW.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
    // Mirror code (1 question)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBE is to YV as JM is to ___",
      options: ["QN", "RO", "PN", "QO"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. B (position 2) mirrors to Y (position 25) because 27-2=25. E (position 5) mirrors to V (position 22) because 27-5=22. Similarly, J (position 10) mirrors to Q (position 17) because 27-10=17, and M (position 13) mirrors to N (position 14) because 27-13=14. So JM → QN.",
      difficulty: 1,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "6-7",
      examBoard: "GL",
    },
  ];

  // Insert all questions
  for (const q of questions) {
    await prisma.question.create({ data: q });
  }

  console.log("✅ Seeded GL Verbal Reasoning Ages 6-7:", questions.length, "questions");
}
