import type { PrismaClient } from "../src/generated/prisma/client.ts";

/**
 * GL Assessment Verbal Reasoning Questions for Ages 9-10
 * 4 question types × 10 questions each = 40 questions (starter set)
 *
 * Question types: synonyms, antonyms, word_completion, odd_one_out
 * Difficulty distribution: 50% easy (2), 40% medium (3), 10% hard (4)
 */

export async function seedGLVerbal910(prisma: PrismaClient) {
  const questions = [
    // Synonyms (10 questions, easier for younger kids)
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'happy'?",
      options: ["sad", "joyful", "angry", "tired"],
      correctAnswer: 1,
      explanation: "'Joyful' means feeling very happy.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'big'?",
      options: ["small", "large", "tiny", "little"],
      correctAnswer: 1,
      explanation: "'Large' means the same as big.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'fast'?",
      options: ["slow", "quick", "tired", "lazy"],
      correctAnswer: 1,
      explanation: "'Quick' means moving or doing something fast.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'small'?",
      options: ["huge", "tiny", "big", "giant"],
      correctAnswer: 1,
      explanation: "'Tiny' means very small.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'nice'?",
      options: ["mean", "kind", "bad", "rude"],
      correctAnswer: 1,
      explanation: "'Kind' means being nice to others.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'cold'?",
      options: ["hot", "chilly", "warm", "sunny"],
      correctAnswer: 1,
      explanation: "'Chilly' means feeling cold.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'brave'?",
      options: ["scared", "fearless", "afraid", "worried"],
      correctAnswer: 1,
      explanation: "'Fearless' means being very brave.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'funny'?",
      options: ["sad", "amusing", "boring", "serious"],
      correctAnswer: 1,
      explanation: "'Amusing' means something that makes you laugh or smile.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'loud'?",
      options: ["quiet", "noisy", "silent", "soft"],
      correctAnswer: 1,
      explanation: "'Noisy' means making a lot of loud sounds.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "synonyms",
      questionText: "Which word is closest in meaning to 'smart'?",
      options: ["silly", "clever", "foolish", "dumb"],
      correctAnswer: 1,
      explanation: "'Clever' means being smart and quick to learn.",
      difficulty: 4,
      tags: ["verbal_reasoning", "vocabulary"],
      ageRange: "9-10",
      examBoard: "GL",
    },

    // Antonyms (10 questions)
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hot'?",
      options: ["warm", "cold", "sunny", "bright"],
      correctAnswer: 1,
      explanation: "'Cold' is the opposite of hot.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'up'?",
      options: ["over", "down", "high", "top"],
      correctAnswer: 1,
      explanation: "'Down' is the opposite of up.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'day'?",
      options: ["morning", "night", "afternoon", "evening"],
      correctAnswer: 1,
      explanation: "'Night' is the opposite of day.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'happy'?",
      options: ["joyful", "sad", "cheerful", "glad"],
      correctAnswer: 1,
      explanation: "'Sad' is the opposite of happy.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'wet'?",
      options: ["damp", "dry", "moist", "soggy"],
      correctAnswer: 1,
      explanation: "'Dry' is the opposite of wet.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'old'?",
      options: ["ancient", "young", "aged", "elderly"],
      correctAnswer: 1,
      explanation: "'Young' is the opposite of old.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'loud'?",
      options: ["noisy", "quiet", "deafening", "booming"],
      correctAnswer: 1,
      explanation: "'Quiet' is the opposite of loud.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'hard'?",
      options: ["tough", "soft", "solid", "firm"],
      correctAnswer: 1,
      explanation: "'Soft' is the opposite of hard.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'full'?",
      options: ["packed", "empty", "stuffed", "complete"],
      correctAnswer: 1,
      explanation: "'Empty' is the opposite of full.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "antonyms",
      questionText: "Which word means the opposite of 'early'?",
      options: ["soon", "late", "prompt", "quick"],
      correctAnswer: 1,
      explanation: "'Late' is the opposite of early.",
      difficulty: 4,
      tags: ["verbal_reasoning", "opposites"],
      ageRange: "9-10",
      examBoard: "GL",
    },

    // Word Completion (10 questions)
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: c_t",
      options: ["a", "o", "i", "u"],
      correctAnswer: 0,
      explanation: "The word is 'cat'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: d_g",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'dog'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: s_n",
      options: ["i", "a", "o", "u"],
      correctAnswer: 3,
      explanation: "The word is 'sun'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: b_ll",
      options: ["i", "e", "a", "o"],
      correctAnswer: 2,
      explanation: "The word is 'ball'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: tr_e",
      options: ["a", "e", "i", "u"],
      correctAnswer: 3,
      explanation: "The word is 'true'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_use",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'house'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fr_end",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'friend'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: fl_wer",
      options: ["a", "e", "i", "o"],
      correctAnswer: 3,
      explanation: "The word is 'flower'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: h_ppy",
      options: ["a", "e", "i", "o"],
      correctAnswer: 0,
      explanation: "The word is 'happy'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "word_completion",
      questionText: "Complete the word: l_ght",
      options: ["a", "e", "i", "o"],
      correctAnswer: 2,
      explanation: "The word is 'light'.",
      difficulty: 4,
      tags: ["verbal_reasoning", "spelling"],
      ageRange: "9-10",
      examBoard: "GL",
    },

    // Odd One Out (10 questions)
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["cat", "dog", "table", "bird"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Table' is the odd one out because it's not an animal.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["red", "blue", "happy", "green"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Happy' is the odd one out because it's not a color.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["apple", "banana", "carrot", "orange"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Carrot' is the odd one out because it's a vegetable, not a fruit.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["run", "jump", "sleep", "hop"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Sleep' is the odd one out because it's not an active movement.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["Monday", "Tuesday", "January", "Friday"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'January' is the odd one out because it's a month, not a day of the week.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["car", "bus", "train", "pencil"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Pencil' is the odd one out because it's not a vehicle.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["hat", "shoe", "sock", "shirt"],
      correctAnswer: 1,
      correctAnswers: [1],
      explanation: "'Shoe' is the odd one out because all others are worn in pairs except the hat.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["book", "pen", "computer", "eraser"],
      correctAnswer: 2,
      correctAnswers: [2],
      explanation: "'Computer' is the odd one out because it's electronic, while others are simple tools.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["circle", "square", "triangle", "purple"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Purple' is the odd one out because it's a color, not a shape.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_wordp",
      questionType: "odd_one_out",
      questionText: "Which word is the odd one out?",
      options: ["elephant", "mouse", "lion", "chair"],
      correctAnswer: 3,
      correctAnswers: [3],
      explanation: "'Chair' is the odd one out because it's not a living animal.",
      difficulty: 4,
      tags: ["verbal_reasoning", "classification"],
      ageRange: "9-10",
      examBoard: "GL",
    },

    // Alphabet Series (10 questions: 1 same operation, 5 different operations, 4 mirror codes)
    // Same operation (1 question)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nRU is to VY as EH is to ___",
      options: ["IL", "JM", "IK", "HK"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "R to V is +4, U to Y is +4. Both letters move forward by 4. E to I is +4, H to L is +4. So EH → IL.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    // Different operations (5 questions)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nAE is to DN as FJ is to ___",
      options: ["IS", "HR", "IT", "JR"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "A to D is +3, E to N is +9. First letter moves forward 3, second letter moves forward 9. F to I is +3, J to S is +9. So FJ → IS.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBG is to EM as KP is to ___",
      options: ["NV", "MT", "OV", "NU"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "B to E is +3, G to M is +6. First letter moves forward 3, second letter moves forward 6. K to N is +3, P to V is +6. So KP → NV.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBH is to FJ as NR is to ___",
      options: ["RT", "QT", "SU", "RS"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "B to F is +4, H to J is +2. First letter moves forward 4, second letter moves forward 2. N to R is +4, R to T is +2. So NR → RT.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nCK is to GN as OS is to ___",
      options: ["SV", "RU", "TV", "SW"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "C to G is +4, K to N is +3. First letter moves forward 4, second letter moves forward 3. O to S is +4, S to V is +3. So OS → SV.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nFM is to IQ as LR is to ___",
      options: ["OV", "NV", "OU", "PW"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "F to I is +3, M to Q is +4. First letter moves forward 3, second letter moves forward 4. L to O is +3, R to V is +4. So LR → OV.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    // Mirror codes (4 questions)
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nBF is to YU as GL is to ___",
      options: ["TO", "SO", "TP", "SP"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. B (position 2) mirrors to Y (position 25) because 27-2=25. F (position 6) mirrors to U (position 21) because 27-6=21. Similarly, G (position 7) mirrors to T (position 20) because 27-7=20, and L (position 12) mirrors to O (position 15) because 27-12=15. So GL → TO.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nDK is to WP as HN is to ___",
      options: ["SM", "TN", "SN", "TM"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. D (position 4) mirrors to W (position 23) because 27-4=23. K (position 11) mirrors to P (position 16) because 27-11=16. Similarly, H (position 8) mirrors to S (position 19) because 27-8=19, and N (position 14) mirrors to M (position 13) because 27-14=13. So HN → SM.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nEJ is to VQ as MR is to ___",
      options: ["NI", "OJ", "MI", "OI"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. E (position 5) mirrors to V (position 22) because 27-5=22. J (position 10) mirrors to Q (position 17) because 27-10=17. Similarly, M (position 13) mirrors to N (position 14) because 27-13=14, and R (position 18) mirrors to I (position 9) because 27-18=9. So MR → NI.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
    {
      topicId: "top_analog",
      questionType: "alphabet_series",
      questionText: "Mark the pair of letters that completes each sentence in the most sensible way. Use the alphabet to help you.\nCP is to XK as GS is to ___",
      options: ["TH", "UH", "TG", "SH"],
      correctAnswer: 0,
      correctAnswers: [0],
      explanation: "This is a mirror pattern using the alphabet. C (position 3) mirrors to X (position 24) because 27-3=24. P (position 16) mirrors to K (position 11) because 27-16=11. Similarly, G (position 7) mirrors to T (position 20) because 27-7=20, and S (position 19) mirrors to H (position 8) because 27-19=8. So GS → TH.",
      difficulty: 4,
      tags: ["verbal_reasoning", "letter_patterns"],
      ageRange: "9-10",
      examBoard: "GL",
    },
  ];

  // Insert all questions
  for (const q of questions) {
    await prisma.question.create({ data: q });
  }

  console.log("✅ Seeded GL Verbal Reasoning Ages 9-10:", questions.length, "questions");
}
